[project]
name = "cxs-orm-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zzstar101", email = "zhanwenxi666@163.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.0",
]

[project.scripts]
cxs-orm-task = "cxs_orm_task:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
